apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-deployment
  labels:
    app: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-detection
        image: remiguy/mise-en-prod-fraud:v2.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000